// desafio 1

algoritmo "Construtor de Data Centers"

var

largura: real
comprimento: real


inicio

escreva("Digite a largura da sala em metros: ")
leia(largura)
escreva("Digite o comprimento da sala em metros: ")
leia(comprimento)

escreva("A área da sala (em metros) é de: " + largura*comprimento)
escreva("O perímetro da sala (em metros) é de: " + (largura+largura+comprimento+comprimento))

fimalgoritmo


