algoritmo "Crachá do técnico"

var
    nome: caractere
    idade: inteiro
    curso: caractere
    n_maquina:inteiro

inicio
    escreval("Digite o seu nome")
    leia(nome)
    escreval("Digite a sua idade")
    leia(idade)
    escreval("Digite o nome do seu curso")
    leia(curso)
    escreval("Digite o número da sua máquina")
    leia(n_maquina)
    escreva("Aluno ",nome," de ", idade, " anos, do curso ",curso,".", n_maquina, " é o número da sua máquina ")

fimalgoritmo